import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Check, ChevronRight, Clock3, Eye, History, LoaderCircle, MapPin, MessageCircle, RotateCcw, Save, Send, Sparkles, Users, Volume2, VolumeX, X } from 'lucide-react';
import { CAST, CHAPTER_PLACES, PHASES, type ChapterView, type ChapterRole, type ChapterPerson, type ChapterPlace } from './lib/chapter-one';
import { useAtmosphere } from './use-atmosphere';
import { useRoleVoice } from './use-role-voice';

type Session={token:string;view:ChapterView};
const CURRENT='wefans-qiluo-chapter-one-v1',BOOKMARK='wefans-qiluo-chapter-one-bookmark-v1';
function stored(key:string):Session|null{try{const s=JSON.parse(localStorage.getItem(key)||'null');return s?.token&&s?.view?.phase?s:null}catch{return null}}
function Avatar({id}:{id:ChapterPerson}){return <span className="ch-avatar" style={{'--person-color':CAST[id].color} as React.CSSProperties}>{CAST[id].initial}</span>}
export default function ChapterOne({onSandbox}:{onSandbox:()=>void}){
  const [session,setSession]=useState<Session|null>(null),[saved,setSaved]=useState<Session|null>(null),[bookmark,setBookmark]=useState<Session|null>(null),[previous,setPrevious]=useState<Session|null>(null);
  const [busy,setBusy]=useState(false),[seconds,setSeconds]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState(''),[text,setText]=useState('');
  const [target,setTarget]=useState<ChapterPerson>('zhuo'),[mode,setMode]=useState<'free'|'say'>('free'),[quiet,setQuiet]=useState(true),[panel,setPanel]=useState<'people'|'memory'>('people');
  const [drawer,setDrawer]=useState(false),[reset,setReset]=useState(false),[autoSaved,setAutoSaved]=useState(true),[connected,setConnected]=useState<boolean|null>(null);
  const voice=useRoleVoice('chapter-one');
  const [autoVoice,setAutoVoice]=useState(()=>{try{return localStorage.getItem('qiluo-chapter-voice')!=='off'}catch{return true}});
  const autoVoiceRef=useRef(autoVoice);
  function toggleVoice(){const next=!autoVoiceRef.current;autoVoiceRef.current=next;setAutoVoice(next);voice.stop();if(next)voice.unlock();try{localStorage.setItem('qiluo-chapter-voice',next?'on':'off')}catch{}}
  const lock=useRef(false),last=useRef<HTMLDivElement>(null);const view=session?.view,atmosphere=useAtmosphere(view?.place==='canopy'||view?.place==='airport'?'terrace':view?.place,Boolean(voice.active));
  useEffect(()=>{setSaved(stored(CURRENT));setBookmark(stored(BOOKMARK));fetch('/api/qiluo/status').then(r=>r.json()).then(d=>setConnected(Boolean(d.configured))).catch(()=>setConnected(false))},[]);
  useEffect(()=>{if(!busy){setSeconds(0);return}const t=setInterval(()=>setSeconds(x=>x+1),1000);return()=>clearInterval(t)},[busy]);
  useEffect(()=>{if(view?.turn)last.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'nearest'})},[view?.turn]);
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(t)},[notice]);
  function persist(next:Session){setSession(next);setSaved(next);try{localStorage.setItem(CURRENT,JSON.stringify(next));setAutoSaved(true)}catch{setAutoSaved(false);setNotice('本机暂时无法保存，当前页面仍可继续。')}if(!next.view.present.includes(target))setTarget(next.view.present[0]||'zhuo');if(!next.view.present.length)setMode('free')}
  async function call(path:string,body:unknown){const r=await fetch('/api/qiluo/chapter/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(100000)});const d=await r.json();if(!r.ok)throw new Error(d.error||'暂时无法连接，请重试。');return d as Session}
  async function open(body:{role:ChapterRole}|{token:string}){if(lock.current)return;voice.stop();voice.unlock();lock.current=true;setBusy(true);setError('');try{persist(await call('session',body));setPrevious(null);setReset(false);setText('');setMode('free');setConnected(true)}catch(e){setError(e instanceof Error?e.message:'连接暂时中断，请重试。')}finally{setBusy(false);lock.current=false}}
  async function turn(action:string,options:Record<string,unknown>={}){if(!session||lock.current)return;if((action==='free'||action==='say')&&!text.trim())return;voice.stop();voice.unlock();lock.current=true;setBusy(true);setError('');try{const next=await call('turn',{token:session.token,requestId:crypto.randomUUID(),action,...options,...(['free','say'].includes(action)?{text:text.trim()}:{}),...(action==='say'?{target,private:quiet}:{})});setPrevious(session);persist(next);if(autoVoiceRef.current){const oldIds=new Set(session.view.messages.map(m=>m.id));void voice.enqueue(next.token,next.view.messages.filter(m=>!oldIds.has(m.id)))}if(action==='free'||action==='say')setText('')}catch(e){setError(e instanceof Error&&!/Timeout|Abort/.test(e.name)?e.message:'回应有些慢，本轮进度没有改变。你可以重试。')}finally{lock.current=false;setBusy(false)}}
  function save(){if(!session)return;try{localStorage.setItem(BOOKMARK,JSON.stringify(session));setBookmark(session);setNotice('这一刻已保存，可以回来换一个选择。')}catch{setNotice('本机空间不足，暂时无法保存。')}}
  const roleCards=<div className="ch-role-grid">{(['chen','zhao'] as ChapterRole[]).map(role=><button key={role} className={'ch-role ch-role-'+role} disabled={busy||connected===false} onClick={()=>open({role})}><Avatar id={role}/><small>以他的视角</small><h2>{CAST[role].name}</h2><p>{role==='chen'?'风雨里先确认他平安，再把一场晚宴安排得妥当。是否走到他面前，由你决定。':'归来的人有许多应酬。今晚意外舒心，你可以只享受片刻，也可以问问缘由。'}</p><b>走进第一章 <ArrowRight size={17}/></b></button>)}</div>;
  const aside=view&&<><div className="ch-tabs"><button className={panel==='people'?'active':''} onClick={()=>setPanel('people')}><Users size={16}/>身边的人</button><button className={panel==='memory'?'active':''} onClick={()=>setPanel('memory')}><History size={16}/>行动的余波</button></div>{panel==='people'?<div className="ch-people">{view.people.map(p=><article key={p.id}><button disabled={!p.nearby||busy} onClick={()=>{setTarget(p.id);setMode('say');setDrawer(false)}}><Avatar id={p.id}/><span><b>{CAST[p.id].name}</b><small>{p.nearby?CHAPTER_PLACES[view.place]:'不在近旁'}</small></span>{p.nearby&&<MessageCircle size={15}/>}</button><p>{CAST[p.id].relation}</p>{p.impressions.map(t=><small className="ch-impression" key={t}>{t}</small>)}</article>)}<p className="ch-note">话传到了谁那里，谁才会回应。别人的心事不会直接写在这里。</p></div>:<div className="ch-memory">{view.events.length===0&&<p>你做过的事，会从这里留下痕迹。</p>}{view.events.slice(-18).reverse().map(e=><article key={e.id}><small>第 {e.turn} 步 · {e.actor==='world'?'这一晚':CAST[e.actor].name}</small><p>{e.text}</p><span>知情：{e.witnesses.map(p=>CAST[p].name).join('、')}</span>{e.cause&&<b>承接此前的行动或消息</b>}</article>)}</div>}<div className="ch-mem-actions"><button disabled={busy||!previous} onClick={()=>previous&&open({token:previous.token})}><RotateCcw size={14}/>回到上一步</button><button disabled={busy||!bookmark} onClick={()=>bookmark&&open({token:bookmark.token})}><BookOpen size={14}/>读取保存的一刻</button></div></>;
  return <div className="ch-app">
    <header className="ch-header"><button className="ch-logo" onClick={()=>{if(!busy){voice.stop();setSession(null);setError('')}}} aria-label="回到章节首页"><img src={window.__QILUO_ASSETS__['/wefans-logo.png']} alt="WeFans"/></button><span>奇洛李维斯回信</span><div><span className="ch-live">第一章试玩</span><button className="ch-sandbox" onClick={onSandbox} disabled={busy}>自由体验旧版 <ArrowRight size={14}/></button></div></header>
    {!view?<main className="ch-start"><div className="ch-cover"><img src={window.__QILUO_ASSETS__['/qiluo-harbour.png']} alt="依山临海的城市"/><div><small>WEFANS · 互动章节 01</small><h1>风球之下</h1><p>外面是风雨。<br/>一场晚宴里，有人归来，有人等候。</p><span>机场归来 → 接风宴 → 檐下散场</span></div></div><section className="ch-start-body"><div className="ch-eyebrow">一个晚上，两种距离</div><h1>先从谁的眼中看？</h1><p className="ch-lead">同一场接风宴，能看见的事并不相同。<br/>可以跟着眼前的机会走，也可以写下自己的行动。</p>{roleCards}{saved&&<button className="ch-resume" disabled={busy} onClick={()=>open({token:saved.token})}><History size={18}/><span>继续上次的第一章 <small>{CAST[saved.view.role].name} · {saved.view.phaseName} · 第 {saved.view.turn} 步</small></span><ArrowRight size={18}/></button>}<div className="ch-start-notes"><span>完整单章 · 双视角 · 不同收尾</span><p>本章合并原著第 1 章及第 2 章餐厅散场前的内容；互动选择可能改变细节与收尾。陈挽与赵声阁的新增对白支持自动语音；雨夜环境声可手动开启。</p><small>{busy?'正在翻开这一章…':connected===null?'正在确认连接…':connected?'已连接在线试玩':'连接暂时不可用，请刷新重试。'}</small></div>{error&&<p className="ch-error" role="alert">{error}</p>}</section></main>:<main className="ch-play">
      <div className="ch-toolbar"><button disabled={busy} onClick={()=>setReset(true)}><ArrowLeft size={16}/>重开 / 换视角</button><span><Avatar id={view.role}/>你是 <b>{CAST[view.role].name}</b></span><div><button disabled={busy} onClick={save}><Save size={16}/>保存这一刻</button><button className="ch-mobile-people" onClick={()=>setDrawer(true)}><Users size={17}/>人物</button></div></div>
      <div className="ch-layout"><section className="ch-story"><div className="ch-stage-cover"><img src={window.__QILUO_ASSETS__['/qiluo-harbour.png']} alt="海湾的雨夜意境"/><div><small>第一章 · 风球之下</small><h1>{view.phaseName}</h1><p>{PHASES.find(p=>p.id===view.phase)?.subtitle}</p></div><span>{String(view.progress+1).padStart(2,'0')}</span></div>
        <ol className="ch-progress" aria-label="章节进度">{PHASES.slice(0,6).map((p,i)=><li key={p.id} className={i<view.progress?'done':i===view.progress?'active':''} aria-current={p.id===view.phase?'step':undefined}><span>{i<view.progress?<Check size={12}/>:i+1}</span>{p.name}</li>)}</ol>
        <div className="ch-ambience"><button onClick={atmosphere.toggle} aria-pressed={atmosphere.enabled}>{atmosphere.enabled?<Volume2 size={15}/>:<VolumeX size={15}/>}雨夜氛围 {atmosphere.enabled?'开':'关'}</button><label>音量<input aria-label="环境音量" type="range" min="0" max="1" step="0.05" value={atmosphere.volume} onChange={e=>atmosphere.setVolume(Number(e.target.value))}/></label><button onClick={toggleVoice} aria-pressed={autoVoice}>{autoVoice?<Volume2 size={15}/>:<VolumeX size={15}/>}角色语音 {autoVoice?'开':'关'}</button>{(voice.active||voice.loading)&&<button onClick={voice.stop}>停止本次播放</button>}</div>{voice.error&&<p className="ch-voice-error" role="status">{voice.error}</p>}
        <div className="ch-transcript" role="log" aria-label="第一章剧情" aria-live="polite" aria-relevant="additions">{view.messages.map(m=><article key={m.id} className={'ch-message '+(m.kind==='chapter'?'ch-chapter-message ':m.speaker==='scene'?'ch-scene-message ':'')+(m.speaker===view.role?'ch-player-message':'')}>{m.speaker!=='scene'&&<div className="ch-message-name"><Avatar id={m.speaker}/><b>{CAST[m.speaker].name}</b><small>{m.speaker===view.role?'你的行动与话':'他的反应'}</small>{m.speech&&['chen','zhao'].includes(m.speaker)&&<button className="ch-voice-play" disabled={!voice.ready[m.speaker as 'chen'|'zhao']} onClick={()=>voice.message(session!.token,m)} aria-label={CAST[m.speaker].name+'：'+(voice.active===m.id?'停止朗读':'朗读这句')} aria-pressed={voice.active===m.id}>{voice.loading===m.id?<LoaderCircle className="qd-spin" size={14}/>:voice.active===m.id?<VolumeX size={14}/>:<Volume2 size={14}/>}<span>{voice.loading===m.id?'生成中':voice.active===m.id?'停止':'听这句'}</span></button>}</div>}<div>{m.text.split('\n').filter(Boolean).map((t,i)=><p key={i}>{t}</p>)}</div></article>)}{busy&&<div className="ch-waiting"><LoaderCircle className="qd-spin" size={17}/><span>{seconds>18?'正在承接你的行动，请稍等…':'故事正在向前…'}{seconds>0&&<small>{seconds} 秒</small>}</span></div>}<div ref={last}/></div>
        {view.ending?<section className="ch-ending"><small>这一局的收尾</small><h2>{view.ending.title}</h2><ul>{view.ending.threads.map(t=><li key={t}><Check size={15}/><span>{t}</span></li>)}</ul><p>这里记下了这一晚真正留下的事。换一个视角，或读回存档，试试另一种走法。</p><div><button onClick={()=>setReset(true)}>换一个视角 <ArrowRight size={16}/></button><button disabled={!bookmark||busy} onClick={()=>bookmark&&open({token:bookmark.token})}>回到保存的一刻</button></div></section>:<>
          <div className="ch-current"><p><MapPin size={15}/><b>{CHAPTER_PLACES[view.place]}</b><span><Clock3 size={13}/>{view.clock}</span></p><div>{view.scene}</div><small>随身：{view.inventory.join(' · ')}</small></div>
          <section className="ch-opportunities"><div className="ch-section-label"><Sparkles size={16}/><b>眼前可以做的事</b><span>也可以自由输入</span></div><div className="ch-choice-grid">{view.choices.map(c=><button key={c.id} disabled={busy} onClick={()=>turn('choice',{id:c.id})}><span>{c.label}<ChevronRight size={16}/></span><p>{c.hint}</p></button>)}</div><button className="ch-continue" disabled={busy} onClick={()=>turn('choice',{id:'continue'})}><span>{view.continueLabel}</span><ArrowRight size={17}/></button></section>
          <section className="ch-compose"><div className="ch-modes"><button className={mode==='free'?'active':''} onClick={()=>setMode('free')}><Sparkles size={15}/>自由行动</button><button className={mode==='say'?'active':''} disabled={!view.present.length} onClick={()=>setMode('say')}><MessageCircle size={15}/>与人交谈</button></div>{mode==='say'?<div className="ch-recipients"><label>对谁说<select value={target} disabled={busy} onChange={e=>setTarget(e.target.value as ChapterPerson)}>{view.present.map(p=><option value={p} key={p}>{CAST[p].name}</option>)}</select></label><label className="ch-private"><input type="checkbox" checked={quiet} onChange={e=>setQuiet(e.target.checked)}/>压低声音，只让他听见</label></div>:<p className="ch-input-hint">动作、对话都可以写。要交代事情，就写清请谁做什么；不必每一步都开口。</p>}
            <form onSubmit={e=>{e.preventDefault();turn(mode)}}><label className="sr-only" htmlFor="chapter-input">你的行动或对话</label><textarea id="chapter-input" maxLength={800} rows={3} value={text} disabled={busy||view.modelCalls>=30} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();turn(mode)}}} placeholder={mode==='say'?`对${CAST[target].name}说些什么…`:'例如：我走到避风廊，暂时不说话，看一会儿雨。'}/><button type="submit" disabled={busy||!text.trim()||view.modelCalls>=30} aria-label="发送行动">{busy?<LoaderCircle className="qd-spin" size={20}/>:<Send size={20}/>}</button></form>
            {error&&<p className="ch-error" role="alert">{error}</p>}{view.modelCalls>=30&&<p className="ch-note">本章自由推演次数已用完。上面的章节选项仍可完整玩到结尾。</p>}
            <div className="ch-small-actions"><button disabled={busy} onClick={()=>turn('observe')}><Eye size={14}/>看看四周</button><button disabled={busy} onClick={()=>turn('wait')}><Clock3 size={14}/>安静等一会儿</button>{view.phase!=='landing'&&<details><summary><MapPin size={14}/>换个位置</summary><div>{(['hall','service','terrace','canopy'] as ChapterPlace[]).map(p=><button key={p} disabled={busy||view.place===p} onClick={()=>turn('move',{place:p})}>{CHAPTER_PLACES[p]}</button>)}</div></details>}</div>
            <footer><span>{autoSaved?'本机已自动保存':'本机保存不可用'} · 第 {view.turn} 步</span><span>自由推演 {view.modelCalls}/30 · {text.length}/800</span></footer>
          </section>
        </>}
      </section><aside className="ch-aside">{aside}</aside></div>
    </main>}
    {notice&&<div className="ch-toast" role="status"><Check size={16}/>{notice}</div>}
    {(reset||drawer)&&<div className="ch-modal-scrim" onClick={()=>{setReset(false);setDrawer(false)}}><section className={'ch-modal '+(drawer?'ch-modal-people':'')} role="dialog" aria-modal="true" aria-label={reset?'重新开始第一章':'人物与记忆'} onClick={e=>e.stopPropagation()}><button className="ch-close" aria-label="关闭" onClick={()=>{setReset(false);setDrawer(false)}}><X size={21}/></button>{reset?<><small>第一章 · 风球之下</small><h2>换个位置，再看这一晚。</h2><p>新开一局会替换自动进度，手动保存的那一刻会保留。</p>{roleCards}{error&&<p className="ch-error">{error}</p>}</>:aside}</section></div>}
  </div>;
}
